### PR TITLE
74 ticket transfer

### PR DESCRIPTION
**Pull request by caudaganesh**
#74

### Breakdown:
- [x] Add user ticket list and redux
- [x] Add attendees list and redux
- [x] Fix login access token async storage

### CODE REVIEW

**Comment by caudaganesh** [comment]
@andy-shi88 sir i need to fix something from this PR

**Comment by andy-shi88** [comment]
ok sure @caudaganesh  let me know if it's ready to be reviewed.

**Comment by caudaganesh** [comment]
it's done now sir, ready for review

**Review by andy-shi88 — APPROVED** [review]
thanks @caudaganesh

**Pull request merged**
