### PR TITLE
58 fix registration menu

### PR DESCRIPTION
**Pull request by rafi-isakh**
This pull request related to issue #58 

### Breakdown:
- [x] Move email and phone button to RegisterMenu
- [x] Register form only show forms with appropriate props.

### CODE REVIEW

**Comment by andy-shi88** [comment]
I think theere is a little miss in the approach to this problem, this way when we click on back button in `registration form` we are getting back to `main screen` and cannot go back to `registrationMenu` later. @rafi-isakh , may be we should navigate to `registrationMenu` when click on the `register` should navigate to `registerMenu` and, further on when we click button on `registerMenu` we will be navigated to registration component.

**Comment by andy-shi88** [comment]
oh wait in #60  PR has fixed this issue. hm, duplicate here, I think we can close this one. thanks and sorry for the trouble @rafi-isakh

**Comment by rafi-isakh** [comment]
okay, how about the phone button and register form? is it also has been covered?

**Comment by andy-shi88** [comment]
yeah actually it is @rafi-isakh :+1:

**Comment by andy-shi88** [comment]
I'll close this one for now.

**Pull request closed without merging**
