### PR TITLE
549 re design ticket ui

### PR DESCRIPTION
**Pull request by denisenricohasyim93**
#549

### CODE REVIEW

**Comment by denisenricohasyim93** [comment]
screen shot 2017-10-24 at 12 31 36

**Comment by akbarrg** [comment]
@denisenricohasyim93 Why the artwork image is duplicated? please fix it. thanks

**Comment by denisenricohasyim93** [comment]
screen shot 2017-10-24 at 13 27 02

how about now?

**Comment by akbarrg** [comment]
@denisenricohasyim93 please remove the console log on render method. Thanks

**Pull request merged**
